services:
  - type: web
    name: tracking-app
    env: java
    plan: free
    buildCommand: ./gradlew build
    startCommand: java -jar build/libs/tracking-app-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
